# Generated by Django 6.1 on 2026-09-27 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='registered_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
